on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: setup-substrate
        uses: ./setup-substrate

      - run: |
          echo "rust version ${{ steps.setup-substrate.outputs.rust-version }}"
          echo "cargo version ${{ steps.setup-substrate.outputs.cargo-version }}"