name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-11
          - macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: setup substrate
        id: setup-substrate
        uses: ./

      - name: tool versions
        run: |
          echo rust version ${{ steps.setup-substrate.outputs.rust-version }}
          echo cargo version ${{ steps.setup-substrate.outputs.cargo-version }}
          echo zombienet version ${{ steps.setup-substrate.outputs.zombienet-version }}