on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup substrate
        id: setup-substrate
        uses: ./

      - name: tool versions
        run: |
          echo rust version ${{ steps.setup-substrate.outputs.rust-version }}
          echo cargo version ${{ steps.setup-substrate.outputs.cargo-version }}
          echo subkey version ${{ steps.setup-substrate.outputs.subkey-version }}
          echo moonkey version ${{ steps.setup-substrate.outputs.moonkey-version }}
          echo subwasm version ${{ steps.setup-substrate.outputs.subwasm-version }}
          echo cargo-contract version ${{ steps.setup-substrate.outputs.cargo-contract-version }}
          echo zombienet version ${{ steps.setup-substrate.outputs.zombienet-version }}